-- 1. Tabla de Notificaciones
CREATE TABLE IF NOT EXISTS public.notificaciones (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    usuario_id UUID NOT NULL REFERENCES public.usuarios(usuario_id) ON DELETE CASCADE,
    titulo TEXT NOT NULL,
    mensaje TEXT NOT NULL,
    tipo TEXT NOT NULL, -- 'bitacora_creada', 'caso_asignado', 'sistema'
    entidad_id TEXT, -- ID del recurso asociado (para redirección rápida)
    leido BOOLEAN NOT NULL DEFAULT false,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Índices de optimización para rendimiento
CREATE INDEX IF NOT EXISTS idx_notificaciones_usuario_leido ON public.notificaciones(usuario_id, leido);
CREATE INDEX IF NOT EXISTS idx_notificaciones_creado_en ON public.notificaciones(creado_en DESC);

-- 2. Tabla para registrar los Tokens Push de Dispositivos (Mobile)
CREATE TABLE IF NOT EXISTS public.tokens_push_usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id UUID NOT NULL REFERENCES public.usuarios(usuario_id) ON DELETE CASCADE,
    token TEXT NOT NULL UNIQUE,
    dispositivo_info JSONB,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_tokens_push_usuario_id ON public.tokens_push_usuario(usuario_id);

-- Habilitar RLS (Row Level Security)
ALTER TABLE public.notificaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tokens_push_usuario ENABLE ROW LEVEL SECURITY;

-- Políticas de Seguridad (RLS)
CREATE POLICY "Permitir lectura de notificaciones propias" 
    ON public.notificaciones FOR SELECT 
    USING (auth.uid() = usuario_id);

CREATE POLICY "Permitir actualizar notificaciones propias" 
    ON public.notificaciones FOR UPDATE 
    USING (auth.uid() = usuario_id);

CREATE POLICY "Permitir inserción de notificaciones (sistema)" 
    ON public.notificaciones FOR INSERT 
    WITH CHECK (true);

CREATE POLICY "Permitir gestión de tokens propios" 
    ON public.tokens_push_usuario FOR ALL 
    USING (auth.uid() = usuario_id);
